title: My Website
description: A simple site hosted on GitHub Pages
theme: jekyll-theme-cayman
baseurl: "/my-website"  # if custom domain, set baseurl:""

# Optional: make sure Jekyll includes your folders
include:
  - _layouts
  - assets/css
