title: My Website
description: A simple site hosted with GitHub Pages and built with a custom layout
# theme: jekyll-theme-cayman

# Optional: make sure Jekyll includes your folders
include:
  - _layouts
  - assets/css
