title: My Website
description: A simple site hosted on GitHub Pages
theme: jekyll-theme-cayman
baseurl: ""  # if custom domain, set baseurl:""; "/my-website" in prod config

# Optional: make sure Jekyll includes your folders
include:
  - _layouts
  - assets/css
